//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdventOfCode2020.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdventOfCode2020.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1789
        ///1818
        ///1729
        ///1578
        ///1927
        ///751
        ///1772
        ///1521
        ///1850
        ///1438
        ///1855
        ///1334
        ///1878
        ///1290
        ///1678
        ///1847
        ///1495
        ///1538
        ///1403
        ///1797
        ///1906
        ///1770
        ///1963
        ///1370
        ///1684
        ///1328
        ///1544
        ///1528
        ///1871
        ///2010
        ///1999
        ///1347
        ///1760
        ///1903
        ///1860
        ///1468
        ///1511
        ///1477
        ///1668
        ///1979
        ///1358
        ///1298
        ///1493
        ///1459
        ///1382
        ///2001
        ///1394
        ///1681
        ///1515
        ///1948
        ///1991
        ///1775
        ///1661
        ///1786
        ///1966
        ///1506
        ///1853
        ///1373
        ///1454
        ///1462
        ///1830
        ///1964
        ///1442
        ///1455
        ///2008
        ///1854
        ///1763
        ///1758
        ///1751
        ///1460
        ///1630
        ///1487
        ///1360
        ///1793
        ///1590
        ///1940
        ///1388
        ///1313
        ///1408
        ///1429
        ///1725
        ///1397
        ///1941
        ///1974
        ///1788
        ///147 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string input_day1_part1 {
            get {
                return ResourceManager.GetString("input_day1_part1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9-12 q: qqqxhnhdmqqqqjz
        ///12-16 z: zzzzzznwlzzjzdzf
        ///4-7 s: sssgssw
        ///13-14 p: pppqzpppppppfpppp
        ///2-9 m: jknmmmmmmdmmmrm
        ///4-5 b: bbbrb
        ///2-10 c: hcpzpjclzc
        ///7-11 f: ffpffffgfrff
        ///4-5 j: qrrhjt
        ///13-14 m: wfwvfxmchplldvm
        ///8-9 l: lllllllll
        ///5-9 v: knvvwptdvmchnkd
        ///1-7 s: sssssqsss
        ///6-14 j: jjjjjbjjjjjjjp
        ///6-8 c: cccccqzf
        ///9-18 h: hhhhchhdhghhhhhhhhch
        ///2-3 s: bssswhs
        ///3-4 c: bhtg
        ///10-13 b: bbbbbbbbbbbbmb
        ///15-16 l: lllllllmlllllllll
        ///3-4 m: dwmmcmn
        ///2-5 h: vqnbh
        ///10-13 n: nnnnnnnnnnnnln
        ///12-13 g: vxgggggggggggggg
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string input_day2 {
            get {
                return ResourceManager.GetString("input_day2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .##.....#....#....#..#.#...#.##
        ///.###........#.##....#......#..#
        ///#..#..#.....#...#....#.#.......
        ///.........#.................#...
        ///..#.......#.#.......#.......#.#
        ///.####........#.#..##.........#.
        ///........#.........#.........#..
        ///#..##...##....#.....##......#..
        ///.........#..............#......
        ///#.........#...##.........#.#...
        ///..............#........##.....#
        ///##....#...........#....#.#...#.
        ///.....#..#.....#...#.#..........
        ///#.......#...#..##........##..#.
        ///.#........#.......#............
        ///.......##.....#.# [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string input_day3 {
            get {
                return ResourceManager.GetString("input_day3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to byr:1971
        ///iyr:2017 hgt:160cm
        ///eyr:2020 ecl:hzl
        ///pid:157096267
        ///
        ///hgt:183cm
        ///pid:368895060
        ///ecl:oth eyr:2020
        ///iyr:2013
        ///byr:1966
        ///
        ///ecl:lzr cid:279 pid:192cm
        ///hcl:1f7352 iyr:2014 hgt:70cm eyr:1983
        ///byr:2004
        ///
        ///hcl:#602927 iyr:2018 byr:1938 ecl:blu
        ///eyr:2024 hgt:172cm
        ///pid:839621424
        ///
        ///ecl:#12f268
        ///hcl:#6b5442
        ///iyr:2012 byr:2011
        ///eyr:1933 pid:189cm hgt:155in
        ///
        ///byr:1954
        ///ecl:gry pid:664227667 eyr:2028
        ///hgt:151cm
        ///iyr:2019
        ///
        ///ecl:gry
        ///byr:1931 iyr:2017
        ///pid:459927933 eyr:2028
        ///hgt:67in hcl:#fffffd
        ///
        ///cid:322 hgt:163cm
        ///byr:1969 hcl:#a97842 pid: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string input_day4 {
            get {
                return ResourceManager.GetString("input_day4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FFBBBFFLRL
        ///BFFBFBFRLR
        ///FFFBBFBRRR
        ///BFFBBBBRRL
        ///FFFBBFBLLR
        ///BBFBFBFLLR
        ///FBBFFBFLRL
        ///BFBFBBFLLL
        ///FBFBBFBLRR
        ///FFFBBBBRLR
        ///FFFFBFFRRL
        ///BFFFBFBLRL
        ///BBFFFBBRLL
        ///FFBFFFBLRL
        ///FBFBFFFRLL
        ///BFFBBBFRRL
        ///BFFFBBFRLR
        ///BBBFFFBRLL
        ///FBBBFFBRLL
        ///FFFBFFBRLL
        ///BBFBFBFLLL
        ///BFFBFFFLRL
        ///BBFBBFFLRL
        ///FBFBBBFRRR
        ///FBBBBFBRRL
        ///FBBFFFFLRL
        ///FFFBBFBLRL
        ///BFFFFFFLLR
        ///FFBFFBBRRR
        ///FFFFBBBRLR
        ///FFFBFFFLRR
        ///FBBFBBFLLL
        ///FBBFBBBRLR
        ///BFFBFFFLLR
        ///FFBFBFFRLL
        ///FFFFBBFLRR
        ///BBFBBBFLRR
        ///BFBFBBBRLR
        ///BFFBBFFLRL
        ///BFFBFFFLLL
        ///FBFFFBFLRR
        ///FFFBBBFRLR
        ///FBBFBBFRLL
        ///BBFFFBBLLL
        ///BBFFFFFLLL
        ///FBFFBBBLLL
        ///FBFFFB [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string input_day5 {
            get {
                return ResourceManager.GetString("input_day5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to donpevkjhymzl
        ///ezyopckdlnvmj
        ///
        ///tqwfdoxvim
        ///imzpqwruhynlca
        ///wkemdqfvigo
        ///
        ///kztsuvpgoheyfdrqbnxmlw
        ///onzbdgsrqxhetkvypfulwm
        ///eomvusqtbnwghfzdyxplkr
        ///lthqvfxbnrpdoekugmzyws
        ///
        ///tlsgumiveq
        ///suevmtgrix
        ///
        ///jpcvhae
        ///kfwg
        ///
        ///scbmvulizfajxwdkohynr
        ///nrwjblvodackhmteufixz
        ///crjnozhvmxuilfdgwbak
        ///cjxfvaklnrmzhodubiw
        ///
        ///wepjrhznqbsdcg
        ///bgkxwdzjpcnh
        ///bzhngpwdjc
        ///
        ///zcwd
        ///bcsdwi
        ///dzwc
        ///cndjtw
        ///widc
        ///
        ///fxcdeujrgyimhtnbl
        ///rgxubfaswmyetdzcpj
        ///
        ///qcyvwlznk
        ///pixvryeqmabkg
        ///oyhwkvslqtu
        ///syfvqkj
        ///
        ///oxaqtvbck
        ///xdaocgmjbhr
        ///
        ///itmqhlrpfkjex
        ///glipefrhqdjt
        ///lfxujtahqrkiep
        ///
        ///r
        ///r
        ///r
        ///r
        ///r [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string input_day6 {
            get {
                return ResourceManager.GetString("input_day6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wavy turquoise bags contain no other bags.
        ///vibrant beige bags contain 4 drab lime bags, 1 muted violet bag, 5 drab plum bags, 5 shiny silver bags.
        ///plaid green bags contain 2 pale olive bags, 1 dark chartreuse bag, 1 vibrant olive bag, 1 pale bronze bag.
        ///plaid fuchsia bags contain 5 dull teal bags, 4 dark beige bags, 4 shiny teal bags, 5 vibrant orange bags.
        ///vibrant coral bags contain 1 dotted blue bag.
        ///drab tan bags contain 5 drab maroon bags, 5 bright silver bags, 2 dim tan bags.
        ///light gray bags contain 3  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string input_day7 {
            get {
                return ResourceManager.GetString("input_day7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to acc +15
        ///jmp +461
        ///acc +6
        ///nop +445
        ///jmp +324
        ///jmp +253
        ///acc -4
        ///acc +22
        ///acc +11
        ///jmp +471
        ///jmp +145
        ///acc +19
        ///jmp -7
        ///jmp +431
        ///nop +66
        ///acc +48
        ///jmp +409
        ///jmp +514
        ///jmp +1
        ///acc +32
        ///jmp +552
        ///acc +21
        ///jmp +317
        ///nop +488
        ///jmp +500
        ///jmp +214
        ///acc +41
        ///jmp +17
        ///acc +19
        ///jmp +1
        ///acc +28
        ///jmp +74
        ///acc +37
        ///acc +46
        ///acc -10
        ///jmp +455
        ///acc +33
        ///jmp +585
        ///acc -13
        ///acc +18
        ///jmp +19
        ///jmp +601
        ///acc +30
        ///jmp +272
        ///acc +18
        ///acc +50
        ///acc +1
        ///acc +29
        ///jmp +50
        ///nop +573
        ///jmp +562
        ///nop +274
        ///jmp +1
        ///acc +6
        ///jmp +1
        ///jmp +64
        ///jmp +1
        ///acc +37
        ///jmp +161
        ///nop +549
        ///acc +21
        ///jmp +1
        ///nop  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string input_day8 {
            get {
                return ResourceManager.GetString("input_day8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 34
        ///46
        ///47
        ///1
        ///21
        ///13
        ///31
        ///39
        ///3
        ///35
        ///49
        ///38
        ///32
        ///28
        ///14
        ///29
        ///23
        ///15
        ///27
        ///12
        ///40
        ///30
        ///5
        ///26
        ///18
        ///17
        ///22
        ///4
        ///6
        ///8
        ///9
        ///7
        ///31
        ///10
        ///11
        ///34
        ///13
        ///25
        ///38
        ///16
        ///14
        ///20
        ///19
        ///15
        ///21
        ///27
        ///52
        ///12
        ///23
        ///36
        ///18
        ///29
        ///17
        ///35
        ///28
        ///32
        ///22
        ///24
        ///45
        ///43
        ///30
        ///31
        ///33
        ///26
        ///53
        ///34
        ///37
        ///38
        ///61
        ///39
        ///40
        ///41
        ///42
        ///44
        ///78
        ///46
        ///47
        ///48
        ///50
        ///63
        ///52
        ///64
        ///54
        ///59
        ///80
        ///56
        ///57
        ///85
        ///72
        ///89
        ///71
        ///75
        ///77
        ///79
        ///81
        ///84
        ///83
        ///88
        ///90
        ///93
        ///139
        ///95
        ///98
        ///102
        ///106
        ///113
        ///135
        ///110
        ///115
        ///127
        ///128
        ///210
        ///182
        ///184
        ///172
        ///221
        ///152
        ///189
        ///163
        ///164
        ///188
        ///171
        ///190
        ///196
        ///193
        ///200
        ///208
        ///204
        ///212
        ///216
        ///263
        ///225
        ///237
        ///242
        ///394
        ///291
        ///315
        ///376
        ///316
        ///433
        ///455
        ///323
        ///406
        ///504
        ///613
        ///396
        ///657
        ///383
        ///404
        ///405
        ///408
        ///412
        ///441
        ///479
        ///453
        ///71 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string input_day9 {
            get {
                return ResourceManager.GetString("input_day9", resourceCulture);
            }
        }
    }
}
